# Generated by Django 5.1.3 on 2024-11-24 14:23

import app_recognize_numbers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[app_recognize_numbers.models.check_image], verbose_name='Image')),
            ],
        ),
    ]
